// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var model, _;

  _ = require('underscore');

  model = require('../models/badges');

  exports.save = function(req, res, next) {
    var badges;
    badges = _.clone(req.body);
    model.save(badges, function(err) {
      if (err) {
        return res.json(503, {
          error: true
        });
      }
    });
    next();
    return model.trim();
  };

  exports.send = function(req, res, next) {
    var badges;
    badges = _.clone(req.body);
    model.send(badges, function(err) {
      if (err) {
        return res.json(503, {
          error: true
        });
      }
      return res.json(200, {
        error: null
      });
    });
    return next();
  };

  exports.get = function(req, res, next) {
    return model.get(function(err, data) {
      if (err) {
        return res.json(503, {
          error: true
        });
      }
      return res.json(200, data);
    });
  };

}).call(this);
