// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var axon, socket;

  axon = require('axon');

  socket = axon.socket('pub');

  socket.bind(1338);

  exports.send = function(badge) {
    return socket.send(badge);
  };

}).call(this);
