// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var client, redis;

  redis = require('redis');

  client = redis.createClient();

  client.on('error', function(err) {
    throw err;
  });

  module.exports = client;

}).call(this);
