// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var broadcast, redis;

  redis = require('../lib/redis');

  broadcast = require('../lib/broadcast');

  exports.save = function(badges, callback) {
    var badge;
    if (!badges.length) {
      return callback(null, null);
    }
    badge = badges.pop();
    return redis.lpush('badges', JSON.stringify(badge), function(err) {
      if (err) {
        return callback(err, null);
      }
      return exports.save(badges, callback);
    });
  };

  exports.trim = function() {
    return redis.ltrim('badges', 0, 9);
  };

  exports.send = function(badges, callback) {
    badges.forEach(broadcast.send);
    return callback(null, null);
  };

  exports.get = function(callback) {
    return redis.lrange('badges', 0, -1, function(err, data) {
      if (err) {
        return callback(err, null);
      }
      return callback(null, data.map(JSON.parse));
    });
  };

}).call(this);
